# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
    - release*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull-request to release
      with:
        destination_branch: "release-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
