# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
    - release*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
  release_pull_request:
    runs-on: ubuntu-latest
    name: Cascade PR
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'release-2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
